name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create install directory
      run: mkdir -p build/{usr/bin,usr/lib,etc}
    - name: Build and install
      run: make install PREFIX=build
