# SPDX-FileCopyrightText: 2024 Fredrik Salomonsson <plattfot@posteo.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Makefile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create install directory
      run: mkdir -p build/{usr/bin,usr/lib,etc}
    - name: Build and install
      run: make install PREFIX=build
    - name: Smoke test baksnapper
      run: ./build/usr/bin/baksnapper --version
    - name: Smoke test baksnapperd
      run: ./build/usr/bin/baksnapperd --version
